### ISSUE TITLE
Folders list only updated at startup

### ISSUE THREAD

**Issue by uglygus** [jonashoechst/Syncthing-BrewBar#3]
If  a new _Shared Folder_ is created by Syncthing while Syncthing Brew-Bar is running  the menu does not reflect the new folder until quit and restarted.

The list of Folders should be recreated on each click of the menu bar icon not just at startup.

**Comment by jonashoechst** [comment]
Fixed in 8af2ffc9b2b5ebaab6f3802addca45c94e7a4f54.
